import type { Metadata } from "next";
import Header from "./components/Header";
import "./global.scss";

export const metadata: Metadata = {
  title: "Print Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
